language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8

env:
  matrix:
    - GENOMICSDB_VERSION=0.6.4-proto-3.0.0-beta-1 CLASSPATH=$TRAVIS_BUILD_DIR/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar:.
    - GENOMICSDB_VERSION=0.7.0-proto-3.0.0-beta-1 CLASSPATH=$TRAVIS_BUILD_DIR/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar:.

install:
  - wget http://repo1.maven.org/maven2/com/intel/genomicsdb/${GENOMICSDB_VERSION}/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar
  - wget http://repo1.maven.org/maven2/com/intel/genomicsdb/${GENOMICSDB_VERSION}/genomicsdb-${GENOMICSDB_VERSION}.jar
  - jar xf genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar libtiledbgenomicsdb.so
  - ldd libtiledbgenomicsdb.so
  - md5sum libtiledbgenomicsdb.so
  - rm -f libtiledbgenomicsdb.so
  - jar xf genomicsdb-${GENOMICSDB_VERSION}.jar libtiledbgenomicsdb.so
  - md5sum libtiledbgenomicsdb.so
  - git clone https://github.com/Intel-HLS/GenomicsDB.git

script:
  - javac -d . $TRAVIS_BUILD_DIR/GenomicsDB/example/java/*.java
  - java TestGenomicsDBImporterWithMergedVCFHeader -L 1:1-100000 -w /tmp/ws -A test0 $TRAVIS_BUILD_DIR/GenomicsDB/tests/inputs/vcfs/t0.vcf.gz
  - java TestGenomicsDB --query query.json
