language: java

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env: GENOMICSDB_VERSION=0.8.1-proto-3.0.0-beta-1+uuid-static CLASSPATH=$TRAVIS_BUILD_DIR/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar:.
    - os: osx
      osx_image: xcode6.4
      env: GENOMICSDB_VERSION=0.8.1-proto-3.0.0-beta-1+uuid-static CLASSPATH=$TRAVIS_BUILD_DIR/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar:.

install:
  - curl -O http://repo1.maven.org/maven2/com/intel/genomicsdb/${GENOMICSDB_VERSION}/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar
  - curl -O http://repo1.maven.org/maven2/com/intel/genomicsdb/${GENOMICSDB_VERSION}/genomicsdb-${GENOMICSDB_VERSION}.jar
  - bash -x ./run_checks.sh 
  - git clone https://github.com/Intel-HLS/GenomicsDB.git

script:
  - javac -d . $TRAVIS_BUILD_DIR/GenomicsDB/example/java/*.java
  - java TestGenomicsDBImporterWithMergedVCFHeader -L 1:1-100000 -w /tmp/ws -A test0 $TRAVIS_BUILD_DIR/GenomicsDB/tests/inputs/vcfs/t0.vcf.gz
  - java TestGenomicsDB --query query.json
