name: Github Actions for testing genomicsdb.jar

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    matrix:
      os: [macOS-10.15, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Print github workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "Listing github workspace..."
          ls $GITHUB_WORKSPACE
          echo "current working dir= `pwd`"
          
      # Runs a single command using the runners shell
      - name: Test published genomicsdb.jar
        run: $GITHUB_WORKSPACE/test_genomicsdbjar.sh
        
